name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      # Handle Issues
      - if: github.event_name == 'issues'
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: codereport
          numOfAssignee: 1
      
      # Handle PRs - use one action that can handle both assignments and reviews
      - if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: .github/auto-assign-config.yml
