name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        name: Cache installed packages
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
         
      - name: Set up Racket
        uses: Bogdanp/setup-racket@v1.12
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'

      - name: Install dependencies
        run: raco pkg install --auto --dependencies fail

      - name: Run tests
        run: raco test .
